Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  # Nginx VM
  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "ubuntu/bionic64"
    nginx.vm.hostname = "demo-ansible-role-nginx"
    nginx.vm.network :private_network, ip: "192.168.56.61"
    nginx.vm.network "forwarded_port", guest: 80, host: 8080

    nginx.vm.provider :virtualbox do |v|
      v.name = "nginx"
      v.memory = 2056
      v.cpus = 2
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    nginx.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = {
        type_of_webserver: "nginx"
      }
      ansible.compatibility_mode = "2.0"
      ansible.inventory_path = "hosts"
      ansible.become = true
    end
  end
end
